services:

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=dbpass
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    volumes:
      - .:/usr/local/src/polls
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
